//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UIA_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlightRecord
    {
        public string Id { get; set; }
        public string UserId { get; set; }
        public string Name { get; set; }
        public string PassportNumber { get; set; }
        public string FlightID { get; set; }
        public int Price { get; set; }
        public System.DateTime Time { get; set; }
        public string Origin { get; set; }
        public string Destination { get; set; }
        public string SeatNo { get; set; }
        public string SeatClass { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Email { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Flight Flight { get; set; }
    }
}
